services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data

  merch-service:
    container_name: merch-service
    build: .
    env_file:
      - .env
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pg_data:
